//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoveInn.DAL.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class event_setting
    {
        public int RowID { get; set; }
        public System.Guid ID { get; set; }
        public Nullable<int> EventID { get; set; }
        public int SettingID { get; set; }
        public string SettingValue { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime ModifiedOn { get; set; }
        public int ModifiedBy { get; set; }
        public bool IsActive { get; set; }
    
        public virtual @event @event { get; set; }
        public virtual setting setting { get; set; }
    }
}
