//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoveInn.DAL.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class post_comment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public post_comment()
        {
            this.post_comment1 = new HashSet<post_comment>();
        }
    
        public int RowID { get; set; }
        public System.Guid ID { get; set; }
        public int PostID { get; set; }
        public Nullable<int> ParentID { get; set; }
        public int ProfileID { get; set; }
        public System.DateTime CommentDate { get; set; }
        public string Author { get; set; }
        public string Email { get; set; }
        public string Website { get; set; }
        public string Comment { get; set; }
        public string Country { get; set; }
        public string IP { get; set; }
        public bool IsApproved { get; set; }
        public bool IsSpam { get; set; }
        public bool IsActive { get; set; }
    
        public virtual post post { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<post_comment> post_comment1 { get; set; }
        public virtual post_comment post_comment2 { get; set; }
        public virtual profile profile { get; set; }
    }
}
