//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoveInn.DAL.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class post_notify
    {
        public int ID { get; set; }
        public int PostID { get; set; }
        public int ProfileID { get; set; }
        public string NotifyAddress { get; set; }
    
        public virtual post post { get; set; }
        public virtual profile profile { get; set; }
    }
}
