//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoveInn.DAL.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class profile_setting
    {
        public int ID { get; set; }
        public int ProfileID { get; set; }
        public int SettingID { get; set; }
        public string SettingValue { get; set; }
    
        public virtual profile profile { get; set; }
        public virtual setting setting { get; set; }
    }
}
