//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoveInn.DAL.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class profile_member
    {
        public int ID { get; set; }
        public int ProfileID { get; set; }
        public int MemberID { get; set; }
        public string Description { get; set; }
        public System.DateTime RequestedDate { get; set; }
        public bool IsAccepted { get; set; }
        public System.DateTime AcceptedOn { get; set; }
        public bool IsActive { get; set; }
    
        public virtual profile profile { get; set; }
        public virtual profile profile1 { get; set; }
    }
}
