//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoveInn.DAL.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class setting
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public setting()
        {
            this.event_setting = new HashSet<event_setting>();
            this.user_setting = new HashSet<user_setting>();
        }
    
        public int ID { get; set; }
        public int SettingCategoryID { get; set; }
        public int SettingDatatypeID { get; set; }
        public string Title { get; set; }
        public string DefaultValue { get; set; }
        public bool IsHidden { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime ModifiedOn { get; set; }
        public int ModifiedBy { get; set; }
        public bool IsActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<event_setting> event_setting { get; set; }
        public virtual profile_setting profile_setting { get; set; }
        public virtual setting_category setting_category { get; set; }
        public virtual setting_datatype setting_datatype { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<user_setting> user_setting { get; set; }
    }
}
